# Project information
site_name: WiCa Notes
site_url: https://boyin.pro/wica-notes/
site_author: Bo Yin
site_description: This is technical notes site for me to record my learning thoughts.

# Repository
repo_name: boyin96/wica-notes
repo_url: https://github.com/boyin96/wica-notes/

# Copyright
copyright: Copyright &copy; 2024 ~ now | Bo Yin

# Navigation
nav:
  - Home: index.md
  - WiCa: 
    - x: x.md
  - Technology:
    - Material for MkDocs: technology/mkdocs.md
  - Blog:
    - blog/index.md

# Theme
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - header.autohide  # 自动隐藏
    - navigation.instant # 自动隐藏
    - navigation.tracking # 地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - content.code.annotate
    - content.action.edit
    - toc.integrate
    - toc.follow
    - navigation.path
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.tabs
    - navigation.prune
    - navigation.footer
    - navigation.sections # 启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.expand # 打开Tab时左侧目录全部展开
    - content.code.copy
    - navigation.indexes # 启用节索引页后，可以将文档直接附加到节
    - search.share # 搜索分享按钮
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    # - search.highlight # 搜索出的文章关键词加入高亮
    # - navigation.tabs.sticky # 启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见

  icon: 
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

  font:
    text: Roboto
    code: Roboto Mono

  language: zh

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - tags:
      tags_file: tags.md
  - blog

extra:
  generator: false # 删除页脚显示“使用 MkDocs 材料制造”

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  analytics: 
    provider: google
    property: G-YPXW9DM0JD
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!

# Latex
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - admonition
  - abbr
  - pymdownx.caret    
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - md_in_html
  - toc:
      permalink: true # 固定标题位置为当前位置
      title: On this page
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - tables

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
