# Project information
site_name: WiCa Notes
site_url: https://boyin.pro/wica-notes/
site_author: Bo Yin
site_description: This is technical notes site for me to record my learning thoughts.

# Repository
repo_name: boyin96/wica-notes
repo_url: https://github.com/boyin96/wica-notes/

# Copyright
copyright: Copyright &copy; 2024 ~ now | Bo Yin

# Navigation
nav:
  - Home: index.md
  - WiCa:
    - Background:
        - wica/background/index.md
        - Linear Algebra: wica/background/linear.md
        - Random Variables: wica/background/x.md
        - Baseband Model: wica/background/x.md
        - Information Theory: wica/background/x.md
        - Estimation Theory: wica/background/x.md
        - Channel Capacity: wica/background/x.md
  - Technology:
    - Material for MkDocs: technology/mkdocs.md
  - Programming: 
    - Markdown Basic Syntax: programming/markdown.md
  - Blog:
    - blog/index.md

# Theme
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - announce.dismiss

    - header.autohide  # 自动隐藏

    - navigation.instant # 自动隐藏
    - navigation.tracking # 地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.path
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.tabs
    - navigation.prune
    - navigation.footer # 页脚可以包含指向当前页面的上一页和下一页的链接
    # - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes # 启用节索引页后，可以将文档直接附加到节
    # - navigation.sections # 启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样

    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.code.copy # 代码块出现复制按钮
    - content.tooltips

    - toc.follow # 当启用目录的锚点跟随时，侧边栏会自动滚动，以便活动锚点始终可见

    - search.share # 搜索分享按钮
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    # - navigation.tabs.sticky # 启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    # - toc.integrate # 启用目录的导航集成后，它始终呈现为左侧导航侧边栏的一部分

  icon: 
    repo: fontawesome/brands/github
    edit: material/file-edit-outline 
    view: material/file-eye-outline

  font:
    text: Roboto
    code: Roboto Mono

  language: zh

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - tags:
      tags_file: tags.md
  - blog
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-authors:
      show_email_address: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/boyin96/wica-notes/
      name: GitHub Repository
      
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bo-yin-453760251/
      name: LinkIn

    - icon: fontawesome/solid/user
      link: https://boyin.pro/
      name: Personal Website

    - icon: fontawesome/solid/paper-plane
      link: mailto:<bborg.yin@gmail.com>
      name: e-mail

  generator: false # 删除页脚显示“使用 MkDocs 材料制造”

  consent:
    title: Cookie 许可
    description: >- 
      我们使用 cookie 来识别您的重复访问和偏好，并衡量我们文档的有效性以及用户是否找到了他们正在搜索的内容。 经您同意，您正在帮助我们改进我们的文档。

  analytics: 
    provider: google
    property: G-YPXW9DM0JD
    feedback:
      title: 此页面是否有帮助？
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            感谢您的反馈意见！
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            感谢您的反馈意见！

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex: # latex支持
      generic: true
  - admonition # admonition
  - abbr
  - pymdownx.caret    
  - pymdownx.details # admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - md_in_html
  - toc:
      permalink: true # 固定标题位置为当前位置
      title: On this page
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件 and admonition
  - meta # 支持Markdown文件上方自定义标题标签等
  - tables

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
